### ISSUE TITLE
Duplicate paginated results

### ISSUE THREAD

**Issue by ObserverOfTime** [subject-f/cubari-proxy#7]
The "view more" button duplicates the 1st page before appending the 2nd.
This is not the case for pages after that.

<details>
<summary>Screenshot</summary>
<img src="https://user-images.githubusercontent.com/24971970/149818649-985f3977-e271-4d67-9114-532c45625961.jpeg" alt="Screenshot"/>
</details>

**Comment by funkyhippo** [comment]
Sorry for the delayed response -- it seems like I misunderstood what data is returned from the view more handlers from Paperback's extensions. I can update it shortly.

**Comment by ObserverOfTime** [comment]
Any chance you also have time to review my PR? :^)

**Comment by funkyhippo** [comment]
Ah I didn't realize it was updated, I'll look at it tonight.
